Typescript strict mode
BearStudio/start-ui-web pull request #167
Opened 2022-02-17 12:37 UTC by ivan-dalmet

Remove all errors with `strict: true` in `tsconfig.json` file

2022-03-03 20:36 UTC, yoannfleurydev requested changes
First little review.

2022-03-04 08:27 UTC, yoannfleurydev commented on src/components/DataList/index.tsx
> +  isHover;
No type for `isHover` ?

2022-03-04 08:28 UTC, HugoPerard approved these changes

2022-03-04 08:55 UTC, DecampsRenan approved these changes

2022-03-04 08:55 UTC, DecampsRenan commented on src/components/DataList/index.tsx
> +  {} as TODO
```suggestion
  {} as Partial<DataListContextValue>
```

2022-03-04 09:23 UTC, ivan-dalmet commented on src/components/DataList/index.tsx
> +  {} as TODO
This will not work ;)

2022-03-04 09:29 UTC, yoannfleurydev approved these changes

2022-03-04 09:29 UTC, merged