feat: add ResponsiveIconButton component
BearStudio/start-ui-web pull request #178
Opened 2022-02-25 14:21 UTC by HugoPerard

Adding a new component : ResponsiveIconButton
This component simplify developer experience for integrate button in responsive interface, you can define custom breakpoint for decides when Button component is replace by an IconButton component

![Capture d’écran 2022-02-25 à 15 20 45](https://user-images.githubusercontent.com/48803115/155730865-2f707914-877b-4213-a1a0-12bfaed3b11c.png)

2022-02-25 14:32 UTC, yoannfleurydev requested changes

2022-02-25 14:32 UTC, yoannfleurydev commented on src/components/ResponsiveIconButton/index.tsx
> +}
Isn't that already available through Chakra UI typings ?

2022-02-25 14:32 UTC, yoannfleurydev commented on src/components/ResponsiveIconButton/index.tsx
> +  to?: string;
Looks like it is not used.

2022-02-26 11:32 UTC, yoannfleurydev commented on src/components/ResponsiveIconButton/docs.stories.tsx
> +import { Stack } from '@chakra-ui/react';
Not used

2022-02-27 14:17 UTC, yoannfleurydev requested changes

2022-03-05 14:27 UTC, yoannfleurydev commented
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&pullRequest=178&id=BearStudio_start-ui&open=AX8xQitHt0XDxvfrvkTT

2022-03-05 14:35 UTC, yoannfleurydev commented on src/components/index.ts
>  export * from './Pagination';
```suggestion
export * from './Pagination';
export * from './ResponsiveIconButton';
```

2022-03-07 17:14 UTC, yoannfleurydev approved these changes

2022-03-09 18:59 UTC, ivan-dalmet approved these changes

2022-03-09 19:48 UTC, merged