feat: add Progress component
BearStudio/start-ui-web pull request #180
Opened 2022-02-25 14:58 UTC by HugoPerard

Adding a new component : **Progress**
This component is composable and split in three component : 

1. Progress: the parent one
2. ProgressLabel: child that permits to display a label, with Progress informations
3. ProgressBar: child display Progress Chakra component

![Capture d’écran 2022-02-25 à 15 58 40](https://user-images.githubusercontent.com/48803115/155737083-5792dd64-7010-4158-9354-c48ddcdff500.png)

2022-02-25 18:39 UTC, yoannfleurydev requested changes

2022-02-25 18:39 UTC, yoannfleurydev commented on src/components/Progress/Progress.tsx
> +}
I'd swap the two blocks to declare the ProgressValues before using them.

```suggestion
export interface ProgressValues {
  completed: number;
  total: number;
  isLoading?: boolean;
}

export const ProgressContext = createContext<ProgressValues>(null);
```

2022-02-25 18:39 UTC, yoannfleurydev commented on src/components/Progress/Progress.tsx
> +      <Stack spacing={1} {...rest} />
```suggestion
      <Stack {...rest} />
```

2022-02-25 18:39 UTC, yoannfleurydev commented on src/components/Progress/Progress.tsx
> +};
```suggestion
};

export const useProgressContext = () => useContext(ProgressContext);
```

2022-02-25 18:39 UTC, yoannfleurydev commented on src/components/Progress/ProgressBar.tsx
> +  const { completed, total, isLoading } = useContext(ProgressContext);
```suggestion
  const { completed, total, isLoading } = useProgressContext();
```

2022-02-25 18:39 UTC, yoannfleurydev commented on src/components/Progress/ProgressLabel.tsx
> +};
```suggestion
export const ProgressLabel: FC<ProgressLabelProps> = ({
  children,
  ...rest
}) => {
  const progressValues = useProgressContext();

  return (
    <Text fontWeight="medium" {...rest}>
      {children(progressValues)}
    </Text>
  );
};
```

2022-03-11 10:31 UTC, ivan-dalmet commented
Thanks for the PR but we will not merge it.
It's more a project specific component because it can be done quickly with same amount of code with Chakra Components & theming :)

```jsx
<Stack spacing="1">
  <Text>10 tasks completed on 30</Text>
  <Progress size="xs" value={10/30*100} />
</Stack>
```

```jsx
<Stack spacing="1">
  <Text>Loading...</Text>
  <Progress size="xs" isIndeterminate />
</Stack>
```

2022-03-11 10:31 UTC, closed without merging