Feat/chakra 2
BearStudio/start-ui-web pull request #220
Opened 2022-05-23 18:48 UTC by Jessy-BAER

Upgrade chakra ui to V2

2022-05-25 05:58 UTC, ivan-dalmet requested changes

2022-05-25 05:58 UTC, ivan-dalmet commented on src/app/admin/users/PageUsers.tsx
> +                <UserStatus isActivatedisplay={user.activated} />
Is there a mistake here?

2022-05-27 12:56 UTC, Jessy-BAER commented on src/app/admin/users/PageUsers.tsx
> +                <UserStatus isActivatedisplay={user.activated} />
fix

2022-05-27 13:04 UTC, yoannfleurydev approved these changes
![bitmoji](https://sdk.bitmoji.com/render/panel/e6b903f1-6f64-4279-8278-acddcd2a0952-a1987ddb-a11e-49bc-8a9b-052f30b8f6ce-v1.png?transparent=1&palette=1&width=246)

2022-05-27 17:37 UTC, merged