Feat: add useSmartNavigate and SmartNavigateLink
BearStudio/start-ui-web pull request #227
Opened 2022-06-01 09:15 UTC by HugoPerard

Adding useSmartNavigate hook and SmartNavigateLink component, for manage smart navigation with automatic complete of state, thats permits to make smart goBack easily

⚠️ This feature need an update of "@testing-library/user-event" version from 13.5.0 to 14.2.0. It was not use in project until now, so that should not cause problem

- [x] Hook useSmartNavigate
- [x] Component SmartNavigateLink
- [x] Storybook
- [x] Tests

2022-06-01 09:42 UTC, yoannfleurydev requested changes

2022-06-01 09:42 UTC, yoannfleurydev commented on src/app/router/smartNavigate/utils.ts
> +  `${location.pathname}${location.search}`;
Missing `location.hash` ? https://developer.mozilla.org/en-US/docs/Web/API/Location

2022-06-01 09:42 UTC, yoannfleurydev commented on src/app/router/smartNavigate/useSmartNavigate.ts
> + * @returns smartGoBack: goBack using state *from* value, or fallbackRoute param if there is no *from*
Are you sure about this documentation as you return only 1 object.

2022-06-01 09:42 UTC, yoannfleurydev commented on src/app/router/smartNavigate/SmartNavigateLink.tsx
> + * @description react-router-dom Link overcoat that add state *from* value for manage smart navigation
```suggestion
 * @description react-router-dom Link state override that add `from` value to handle smart navigation.
```

2022-06-11 10:39 UTC, Jessy-BAER commented on package.json
> +    "@testing-library/user-event": "14.2.0",
Are you sure your need it for your feature ?

2022-06-11 10:39 UTC, Jessy-BAER commented on src/app/router/useGoBack.ts
> +export const useGoBack = (defaultFallback?: string) => {
You must add comments on this custom hook

2022-06-11 10:39 UTC, Jessy-BAER commented on src/app/router/Router.tsx
> +export const Router = ({
It's a new important component, please add comments on it

2023-04-28 09:48 UTC, HugoPerard commented
Sonar detects 1 code smell for an unnecessary assertion because that doesn't change type, but if I don't do it there is a typescript error. Because default type is unknown, not any

2023-12-22 22:35 UTC, yoannfleurydev commented
Related to `react-router-dom` that we do not use anymore, I'm closing this PR.

2023-12-22 22:35 UTC, closed without merging