Gérer l'erreur call api list user
BearStudio/start-ui-web pull request #257
Opened 2022-07-19 09:43 UTC by AzizOuertani

j'ai ajouté un message d'erreur lors du chargement de la liste des utilisateurs et ajouter une bouton refresh pour rafraîchir la page. .
![image](https://user-images.githubusercontent.com/109508360/179720265-21850576-001d-4f1f-a37f-1a1d19395650.png)

2022-07-20 09:02 UTC, Jessy-BAER commented on src/locales/fr/users.json
> +      "ReloadPage": "Recharger la page"
The key does not start with uppercase

2022-07-20 11:42 UTC, ivan-dalmet commented on src/app/admin/users/PageUsers.tsx
> +                    onClick={() => window.location.reload()}
In this case we don't want the whole page to reload but just refetch the query from react-query.
Don't use window.location.reload() here ;)

2022-07-21 09:55 UTC, Jessy-BAER approved these changes

2022-07-21 11:09 UTC, ivan-dalmet requested changes
The normal loading behavior is broken 😉
If you refocus the window or on page changed, we should not see a hard loading state

In this case, `isLoadingPage` should not be used to display or not the datalist 😉

https://user-images.githubusercontent.com/9749061/180200079-a3846091-0542-442d-973c-3d19ecc5d00e.mov

2022-07-21 11:24 UTC, ivan-dalmet commented
Also @AzizOuertani can we have a little video demo of the error behavior? (because we can't get an error in the preview env)

2022-07-21 12:51 UTC, AzizOuertani commented
> Also @AzizOuertani can we have a little video demo of the error behavior? (because we can't get an error in the preview env)


https://user-images.githubusercontent.com/109508360/180217630-8930aa41-4e7e-4021-a326-dd44d51ab04b.mp4

2022-08-24 06:16 UTC, Jessy-BAER commented
Maybe we must fix the display in footer, "Showing 1 to 0 of 0 results" seems to be not good ? @ivan-dalmet  are you ok with this ?

2022-08-24 06:21 UTC, ivan-dalmet commented
> Maybe we must fix the display in footer, "Showing 1 to 0 of 0 results" seems to be not good ? @ivan-dalmet  are you ok with this ? 

Yes but it can be in another PR

2022-08-26 13:03 UTC, Malek-khannoussi commented on src/app/admin/users/PageUsers.tsx
> +              <DataListCell gap={4}>
remove the `m="auto"` from the childrens and `justifyContent="center"`

2022-08-26 13:03 UTC, Malek-khannoussi commented on src/app/admin/users/PageUsers.tsx
> +                <Box m="auto">
remove `Box` you dont need it

2022-09-13 11:24 UTC, ivan-dalmet approved these changes

2022-09-13 11:40 UTC, merged