add editable component
BearStudio/start-ui-web pull request #33
Opened 2021-02-11 14:01 UTC by omair2010

## Description 
ajouter le code de Editable text area

https://github.com/BearStudio/start-ui/issues/31

2021-02-11 17:12 UTC, HugoPerard requested changes
Component do not work, text should be staying visible in non-editing state

2021-02-11 17:12 UTC, HugoPerard commented on src/components/Editable/index.tsx
> +            aria-label={t('components.editable.cancel')}
Remove i18n keys, write text directly

2021-02-11 17:12 UTC, HugoPerard commented on src/components/Editable/index.tsx
> +              : t('components.editable.edit')
Remove i18n keys, write text directly

2021-02-11 17:12 UTC, HugoPerard commented on src/components/Editable/index.tsx
> +        />
Maybe you should extract TextareaAutosize component, all these properties are required ?

2021-02-12 13:47 UTC, HugoPerard commented on src/components/TextareaAutosize/Editable.stories.tsx
> +import { TextareaAutosize } from '.';
Wrong file name

2021-02-12 14:04 UTC, HugoPerard commented on src/components/TextareaAutosize/index.tsx
> +    autoFocus
These properties (maybe not minH) should be only on the TextareaAutosize of the Editable

2021-02-12 14:21 UTC, omair2010 commented on src/components/Editable/index.tsx
> +  onCancel?: (string) => void;
we need argument

2022-03-10 11:10 UTC, closed without merging