feat: Add Portuguese language
BearStudio/start-ui-web pull request #387
Opened 2023-06-16 19:43 UTC by qlereboursBS

## Describe your changes

I added the Portuguese language. However it has been translated with ChatGPT and it needs to be validated because I don't speak a word of Portuguese 😄
For instance, the "Admin" nav stays "Admin" but I'm not sure if it should be the case

Also, I saw something that may be a mistake: The text content of the DemoLoginHint component (This is a read-only demo, but you can log in with admin/admin ......) is hard coded, even though it's also translated in the translation files. Is it like this on purpose?

## Screenshots

<img width="1184" alt="image" src="https://github.com/BearStudio/start-ui-web/assets/27200095/af7fec32-16cd-45d7-bb74-9fd41f82f295">
<img width="206" alt="image" src="https://github.com/BearStudio/start-ui-web/assets/27200095/e2b812b4-de56-4bd4-b913-31ca61bf8410">
<img width="641" alt="image" src="https://github.com/BearStudio/start-ui-web/assets/27200095/976f4fee-af6a-4f61-9273-76fe78ed49ab">
<img width="1160" alt="image" src="https://github.com/BearStudio/start-ui-web/assets/27200095/60608523-f267-48f0-94db-4268a18f73c5">

## Documentation

Nothing to add in the documentation.

## Checklist

 - [x] I performed a self review of my code
 - [x] I ensured that everything is written in English
 - [x] I tested the feature or fix on my local environment
 - [x] I ran the `yarn storybook` command and everything is working
 - [x] If applicable, I updated the translations for english and french files  
      (If you cannot update the french language, just let us know in the PR description)
 - [x] If applicable, I updated the README.md
 - [x] If applicable, I created a PR or an issue on the [documentation repository](https://github.com/bearstudio/start-ui-web-docs/)
 - [x] If applicable, I’m sure that my feature or my component is mobile first and available correctly on desktop

2023-06-21 11:22 UTC, ivan-dalmet approved these changes

2023-06-21 11:30 UTC, ivan-dalmet commented
For the hard coded text of DemoLoginHint, it's normal that it's hard coded but there should not be the keys in the translations, you're right. If you can remove the unused keys for that 🙏

2023-06-22 11:44 UTC, qlereboursBS commented
Ok @ivan-dalmet I just removed the translation file because any translation was used

2023-07-07 09:01 UTC, taorepoara commented
On which version should I base the review, the French one or the English one ?

2023-07-07 11:35 UTC, taorepoara requested changes
Some changes needed

2023-07-07 11:35 UTC, taorepoara commented on src/locales/pt/users.json
> +      "createUser": "Criar Usuário"
```suggestion
    "title": "Gerenciamento de usuários",
    "actions": {
      "createUser": "Criar usuário"
```

2023-07-07 11:35 UTC, taorepoara commented on src/locales/pt/users.json
> +      "title": "Usuário Ativado",
```suggestion
      "title": "Usuário ativado",
```

2023-07-07 11:35 UTC, taorepoara commented on src/locales/pt/users.json
> +      "title": "Usuário Desativado",
```suggestion
      "title": "Usuário desativado",
```

2023-07-07 11:35 UTC, taorepoara commented on src/locales/pt/users.json
> +      "title": "Usuário Excluído",
```suggestion
      "title": "Usuário excluído",
```

2023-07-07 11:35 UTC, taorepoara commented on src/locales/pt/users.json
> +      "label": "Nome de Usuário",
```suggestion
      "label": "Nome de usuário",
```

2023-07-07 11:35 UTC, taorepoara commented on src/locales/pt/users.json
> +      "invalid": "Nome de usuário é inválido, não use caracteres especiais"
```suggestion
      "required": "O nome de usuário é obrigatório",
      "tooShort": "O nome de usuário é muito curto (mín. {{min}} caracteres)",
      "tooLong": "O nome de usuário é muito longo (máx. {{max}} caracteres)",
      "invalid": "O nome de usuário é inválido, não use caracteres especiais"
```

2023-07-07 11:35 UTC, taorepoara commented on src/locales/pt/users.json
> +      "tooLong": "E-mail é muito longo (máx. {{max}} caracteres)"
There is diff here with the `account.json`. Both `email` and `e-mail` are used in Portuguese, you should choose one to use...

```suggestion
      "required": "O email é obrigatório",
      "invalid": "O email é inválido",
      "tooShort": "O email é muito curto (mín. {{min}} caracteres)",
      "tooLong": "O email é muito longo (máx. {{max}} caracteres)"
```

2023-07-07 11:35 UTC, taorepoara commented on src/locales/pt/users.json
> +      "label": "Modificado Por"
```suggestion
      "label": "Modificado por"
```

2023-07-07 11:35 UTC, taorepoara commented on src/locales/pt/users.json
> +      "label": "Primeiro Nome"
```suggestion
      "label": "Nome"
```

2023-07-07 11:35 UTC, taorepoara commented on src/locales/pt/users.json
> +      "label": "Último Nome"
```suggestion
      "label": "Sobrenome"
```

2023-07-07 11:35 UTC, taorepoara commented on src/locales/pt/users.json
> +      "save": "Atualizar Usuário"
```suggestion
      "save": "Atualizar usuário"
```

2023-07-07 11:35 UTC, taorepoara commented on src/locales/pt/users.json
> +        "title": "Falha na Criação"
```suggestion
        "title": "Falha na criação"
```

2023-07-07 11:35 UTC, taorepoara commented on src/locales/pt/users.json
> +    "title": "Criar Novo Usuário"
```suggestion
      "save": "Criar usuário"
    },
    "title": "Criar novo usuário"
```

2023-07-07 11:35 UTC, taorepoara requested changes
Some changes needed

2024-01-12 14:29 UTC, yoannfleurydev commented
Hey @qlereboursBS , since we released the "v2" of 🚀 Start UI [web], we'll need you to update this PR if possible. Thanks.

2024-01-21 22:30 UTC, qlereboursBS commented
> Hey @qlereboursBS , since we released the "v2" of 🚀 Start UI [web], we'll need you to update this PR if possible. Thanks.

Ok, I plan to do it next week

2024-07-22 15:53 UTC, closed without merging