Update day picker component
BearStudio/start-ui-web pull request #413
Opened 2023-10-21 11:08 UTC by DecampsRenan

## Describe your changes

Update the day picker component.

## Screenshots

## Checklist

 - [ ] I performed a self review of my code
 - [ ] I ensured that everything is written in English
 - [ ] I tested the feature or fix on my local environment
 - [ ] I ran the `yarn storybook` command and everything is working
 - [ ] If applicable, I updated the translations for english and french files  
      (If you cannot update the french language, just let us know in the PR description)
 - [ ] If applicable, I updated the README.md
 - [ ] If applicable, I created a PR or an issue on the [documentation repository](https://github.com/bearstudio/start-ui-web-docs/)
 - [ ] If applicable, I’m sure that my feature or my component is mobile first and available correctly on desktop

2023-10-23 06:59 UTC, yoannfleurydev requested changes

2023-10-23 06:59 UTC, yoannfleurydev commented on src/components/MonthPicker/months.ts
> +];
What about translations?

2023-10-24 07:55 UTC, DecampsRenan commented on src/components/MonthPicker/months.ts
> +];
Good catch, on it

2023-11-04 22:14 UTC, yoannfleurydev commented on src/components/DayPicker/_partials/DayPickerContent.tsx
> +                  selected={value ? value : undefined}
Maybe?

```suggestion
                  selected={value || undefined}
```

2023-11-14 12:42 UTC, merged