WIP: Feat: TODO: translation password
BearStudio/start-ui-web pull request #510
Opened 2024-07-24 07:24 UTC by Nikola-BS

## Describe your changes

closes #<issue_id>

## Screenshots

## Documentation

## Checklist

 - [ ] I performed a self review of my code
 - [ ] I ensured that everything is written in English
 - [ ] I tested the feature or fix on my local environment
 - [ ] I ran the `pnpm storybook` command and everything is working
 - [ ] If applicable, I updated the translations for english and french files  
      (If you cannot update the french language, just let us know in the PR description)
 - [ ] If applicable, I updated the README.md
 - [ ] If applicable, I created a PR or an issue on the [documentation repository](https://github.com/bearstudio/start-ui-web-docs/)
 - [ ] If applicable, I’m sure that my feature or my component is mobile first and available correctly on desktop

2024-07-24 14:32 UTC, charlelisefouasse requested changes

2024-07-24 14:32 UTC, charlelisefouasse commented on src/components/Form/FieldPassword/index.tsx
> +  const { t } = useTranslation(['common', 'components']);
```suggestion
  const { t } = useTranslation(['components']);
```
il est pas utile le common ?

2024-07-24 14:32 UTC, charlelisefouasse commented on src/components/Form/FieldPassword/index.tsx
> +                    : t('components:fieldPassword.passwordShow')
```suggestion
                    ? t('components:fieldPassword.hidePassword')
                    : t('components:fieldPassword.showPassword')
```
je trouve ca plus logique dans ce sens

2024-07-24 15:15 UTC, charlelisefouasse approved these changes

2024-07-26 06:54 UTC, yoannfleurydev approved these changes

2024-07-26 06:54 UTC, merged